version: '3'
services:
  fsd-app:
    image: fsd-app:1.0
    build: .
    ports:
      - "3000"
    labels: 
      - "traefik.frontend.rule=Host:fsd-app.example.com"
    environment:
      - MONGOLAB_URI: mongodb://mongo:27017/myappdb
      - REDIS_HOST: redis
    depends_on:
     - mongo
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo:4.0.4
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  reverse-proxy:
    image: traefik
    command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
 
    